shallow_clone: true
version: '{build}'
skip_tags: true
environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '0'
    - nodejs_version: '0.10'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm uninstall --save-dev @shinnn/eslint-config-node-legacy eslint
  - npm install
build: off
test_script:
  - node test\test.js
  - If Not %nodejs_version%==0.10 node test\test-broken-npm.js
  - If Not %nodejs_version%==0.10 node test\test-no-npm.js
cache: node_modules -> package.json
